DEV_AWS_BUCKET : 'shouter' #ENV['AWS_BUCKET'],
DEV_AWS_ACCESS_KEY_ID: 'AKIAIRZQKABYBWRUTCDQ' #ENV['AWS_ACCESS_KEY_ID']
DEV_AWS_SECRET_ACCESS_KEY: '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' # ENV['AWS_SECRET_ACCESS_KEY']

# PRO_AWS_BUCKET : 'hamsafaryab.production' #ENV['AWS_BUCKET'],
# PRO_AWS_ACCESS_KEY_ID: 'AKIAJJYF3VETKWDDFGBA' #ENV['AWS_ACCESS_KEY_ID']
# PRO_AWS_SECRET_ACCESS_KEY: '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' # ENV['AWS_SECRET_ACCESS_KEY']
PRO_AWS_BUCKET : 'shouter' #ENV['AWS_BUCKET'],
PRO_AWS_ACCESS_KEY_ID: 'AKIAIRZQKABYBWRUTCDQ' #ENV['AWS_ACCESS_KEY_ID']
PRO_AWS_SECRET_ACCESS_KEY: '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' # ENV['AWS_SECRET_ACCESS_KEY']

GMAIL_USER_NAME: 'hamsafaryab@gmail.com'
GMAIL_PASSWORD: 'pectaiyocwaodpjq'