development:
  adapter: postgresql
  encoding: unicode
  database: shouter_development
  pool: 5
  username: postgres
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: shouter_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: shouter_production
  pool: 5
  username: shouter
  password:
